w5d1/RedditClone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :subs

  resources :posts do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :destroy, :show]

end

w5d1/RedditClone/app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :author_id, :post_id, presence: true

  belongs_to :author,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :post, dependent: :destroy

  belongs_to :parent_comment,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :child_comments,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

end

w5d1/RedditClone/app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :subs, :author_id, presence: true

  belongs_to :user,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :post

  has_many :subs, through: :post_subs

  has_many :comments, dependent: :destroy

end

w5d1/RedditClone/app/models/post_sub.rb
class PostSub < ActiveRecord::Base

  validates :sub, :post, presence: true

  belongs_to :sub

  belongs_to :post

end

w5d1/RedditClone/app/models/sub.rb
class Sub < ActiveRecord::Base

  validates :title, :description, :moderator_id, presence: true

  belongs_to :user,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :sub

  has_many :posts, through: :post_subs

end

w5d1/RedditClone/app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :subs, dependent: :destroy,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :comments,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Comment

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)

  end

  def reset_session_token
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save
    self.session_token
  end

end

w5d1/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
    return nil if @current_user.nil?
    @current_user
  end

  def logged_in?
    return true if current_user
    false
  end

  def login(user)
    session[:session_token] = user.reset_session_token
  end

  def logout
    current_user.reset_session_token if current_user
    session[:session_token] = nil
  end

  def require_user
    redirect_to new_session_url unless current_user
  end

end

w5d1/RedditClone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :require_user

  def show
    @comment = Comment.find_by_id(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash[:errors] = @comment.errors,full_messages
      redirect_to post_url(@comment.post)
    end
  end

  def destroy
    @comment = Comment.find_by_id(params[:id])
    post = @comment.post
    @comment.destroy
    redirect_to post_url(post)
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :content, :parent_comment_id)
  end

end

w5d1/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_user

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  def new
    @post = Post.new
    @subs = Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      @subs = Sub.all
      render :new
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
    @subs = Sub.all
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.author_id != current_user.id
      flash[:errors] = ["can only edit your own post"]
      redirect_to post_url(@post)
    elsif @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      @subs = Sub.all
      render :edit
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    if @post.author_id != current_user.id
      flash[:errors] = ["can only delete your own post"]
      redirect_to post_url(@post)
    else
      @post.destroy
      redirect_to posts_url
    end
  end

  def post_params
    params.require(:post).permit(:title, :content, :url, sub_ids: [])
  end

end

w5d1/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :require_user

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user.nil?
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    else
      login(@user)
      redirect_to subs_url
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

w5d1/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_user

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by_id(params[:id])
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by_id(params[:id])
  end

  def update
    @sub = Sub.find_by_id(params[:id])
    if @sub.moderator_id != current_user.id
      flash[:errors] = ["Can only edit your own sub"]
      redirect_to subs_url
    elsif @sub.update(sub_params)
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find_by_id(params[:id])
    if @sub.moderator_id != current_user.id
      flash[:errors] = ["Can only delete your own sub"]
      redirect_to subs_url
    else
      @sub.destroy
      redirect_to subs_url
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

w5d1/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

w5d1/RedditClone/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end

end

w5d1/RedditClone/app/helpers/comments_helper.rb
module CommentsHelper
end

w5d1/RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

w5d1/RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

w5d1/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

w5d1/RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

w5d1/RedditClone/app/views/comments/new.html.erb
<h2>Add Comment</h2>

<form action='/comments' method="post">
  <%= auth_token %>

  <p>Content</p>
  <label for="content"></label>
  <textarea id="content" name="comment[content]" rows="8" cols="40"></textarea>

  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">
  <br>

  <input type="submit" value="Add Comment">

</form>

w5d1/RedditClone/app/views/comments/show.html.erb
<h2>Comment</h2>

<%= 'Comment for ' + @comment.post.title %><br>
<%= 'Author : ' + @comment.author.email %><br>
<%= @comment.content %><br>


<p>Reply to this comment</p>
<form action='/comments' method="post">

  <%= auth_token %>

  <label for="content"></label>
  <textarea id="content" name="comment[content]" rows="8" cols="40"></textarea>

  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <br>

  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">

  <input type="submit" value="Add Comment">

</form>

w5d1/RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <%= current_user.email %><br>
    <%= link_to 'Sign Out', '/session', method: :delete %>
  <% else %>
    <%= link_to 'Sign Up', new_user_url, method: :get %>
    <%= link_to 'Sign In', new_session_url, method: :get %>
  <% end %>
<br>
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %><br>
  <% end %>
<% elsif flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

w5d1/RedditClone/app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <%= auth_token %>

  <label for="title">Title</label>
  <input id="title" type="text" name="post[title]" value="<%= @post.title %>"><br>

  <p>Content</p>
  <label for="content"></label>
  <textarea id="content" name="post[content]" rows="8" cols="40" value="<%= @post.content %>"></textarea><br>

  <label for="url">URL</label>
  <input id="url" type="text" name="post[url]" value="<%= @post.url %>"><br>

  <label>Choose Subs</label>

  <input type="hidden" name="post[sub_ids][]" value="">
  <br>

  <% @subs.each do |sub| %>
    <label for="Sub">
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if @post.sub_ids.include?(sub.id) %>>
      <%= sub.title %><br>
    </label>
  <% end %>

  <br>
  <input type="submit" value="Edit Post">

</form>

<br>
<%= link_to 'All Posts', posts_url, method: :get %>

w5d1/RedditClone/app/views/posts/index.html.erb
<h2>All Posts</h2>

<% @posts.each do |post| %>
  <%= link_to post.title, post_url(post), method: :get %><br>
  <%= 'Author : ' + post.user.email %>
  <%= '  URL : ' + post.url %><br><br>
<% end %>

<br>

<%= link_to 'Make New Post', new_post_url, method: :get %><br>
<%= link_to 'All Subs', subs_url, method: :get %>

w5d1/RedditClone/app/views/posts/new.html.erb
<h2>Make A New Post</h2>

<form action='/posts' method="post">
  <%= auth_token %>

  <label for="title">Title</label>
  <input id="title" type="text" name="post[title]" value="<%= @post.title %>"><br>

  <p>Content</p>
  <label for="content"></label>
  <textarea id="content" name="post[content]" rows="8" cols="40" value="<%= @post.content %>"></textarea><br>

  <label for="url">URL</label>
  <input id="url" type="text" name="post[url]" value="<%= @post.url %>"><br>

  <label>Choose Subs</label>

  <br>
  <input type="hidden" name="post[sub_ids][]" value="">

  <% @subs.each do |sub| %>
    <label for="Sub">
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if @post.sub_ids.include?(sub.id) %>>
      <%= sub.title %><br>
    </label>
  <% end %>

  <br>
  <input type="submit" value="Create Post">

</form>

<br>
<%= link_to 'All Posts', posts_url, method: :get %>

w5d1/RedditClone/app/views/posts/show.html.erb
<h2>  <%= @post.title %>  </h2>
<br>

<b>Author</b>
<%= @post.user.email %><br>
<br>

<b>Content</b><br>
<%= @post.content %><br>
<br>

<b>Comments</b><br>
<% @post.comments.where(parent_comment_id: nil).each do |comment| %>
  <ul>
    <li>
      <%= comment.content %><br>
      <%= link_to 'View Comment', comment_url(comment), method: :get %><br>
      <% comment.child_comments.each do |child_comment| %>
      <ul>
        <li>
          <%= child_comment.content %>
        </li>
      </ul>
      <% end %>
    </li>
  </ul>
<% end %>

<%= link_to 'Comment On This Post', new_post_comment_url(@post), method: :get  %>

<br><br>
<b>Associated Subs</b><br>
<% @post.subs.each do |sub| %>
  <%= link_to sub.title, sub_url(sub), method: :get %><br>
<% end %>

<br>
<% if current_user.id = @post.author_id %>
  <%= link_to 'Edit Post', edit_post_url(@post), method: :get %><br>
  <%= link_to 'Delete Post', post_url(@post), method: :delete %><br>
<% end %>
<br>


<%= link_to 'All Posts', posts_url, method: :get %><br>
<%= link_to 'All Subs', subs_url, method: :get %>

w5d1/RedditClone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action=  <%= sub_url(@sub) %> method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>

  <label for="title">Title</label>
  <input type="text" name="sub[title]" value="<%= @sub.title %>">

  <label for="description">Description</label>
  <textarea id="description" name="sub[description]" rows="8" cols="40" value="<%= @sub.description %>"></textarea>

  <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">

  <input type="submit" value="Edit Sub">

</form>

w5d1/RedditClone/app/views/subs/index.html.erb
<h2>All Subs!</h2>

<% @subs.each do |sub| %>
  <%= link_to sub.title, sub_url(sub), method: :get %><br>
  <%= 'Owned by : ' + sub.user.email %><br><br>
<% end %>
<br><br>

<%= link_to 'Make New Sub', new_sub_url, method: :get %>
<br>
<%= link_to 'All Posts', posts_url, method: :get %>

w5d1/RedditClone/app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action='/subs' method="post">
  <%= auth_token %>

  <label for="title">Title</label>
  <input type="text" name="sub[title]" value="<%= @sub.title %>">

  <label for="description">Description</label>
  <textarea id="description" name="sub[description]" rows="8" cols="40" value="<%= @sub.description %>"></textarea>

  <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">

  <input type="submit" value="Create New Sub">

</form>

w5d1/RedditClone/app/views/subs/show.html.erb
<h2>  <%= @sub.title %>  </h2>
<br>

<b>Description</b><br><br>
<%= @sub.description %>
<br><br>

<b>Associated Posts</b>
<ul>
  <% @sub.posts.each do |post| %>
    <li>
      <%= link_to post.title, post_url(post), method: :get %>
    </li>
  <% end %>
</ul>
<br>

<%= link_to 'Edit Sub', edit_sub_url(@sub), method: :get %><br>
<%= link_to 'Delete Sub', sub_url(@sub), method: :delete %><br>
<%= link_to 'Make New Post', new_post_url, method: :get %><br>
<%= link_to 'All Subs', subs_url, method: :get %>

w5d1/RedditClone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action='/users' method="post">

  <%= auth_token %>

  <label for="email">Email</label>
  <input id="email" type="text" name="user[email]">

  <label for="Password">Password</label>
  <input id="Password" type="password" name="user[password]">

  <input type="submit" value="Sign Up">

</form>